server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: "/(.*)"
        replacement: "$1"

      - source_labels: [__meta_docker_container_name]
        target_label: container_name
        regex: "/(.*)"
        replacement: "$1"

      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

      - source_labels: [__meta_docker_container_name]
        target_label: job
        replacement: "docker-logs"

      # This is the critical line that tells Promtail where logs are
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
        replacement: /var/lib/docker/containers/*/*.log