FROM jenkins/inbound-agent:latest

USER root

# Install Node.js 18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
  && apt install -y nodejs \
  && npm install -g npm@latest

USER jenkins