FROM jenkins/inbound-agent:latest

USER root

# Install Docker CLI
RUN apt-get update && apt-get install -y \
  docker.io \
  curl

# Install Node.js 24.x
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - \
  && apt install -y nodejs \
  && npm install -g npm@latest

# 👉 Install Infisical CLI
RUN curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | bash && \
    apt-get update && apt-get install -y infisical


# Add jenkins user to docker group with GID 988 (host Docker group)
RUN usermod -aG docker jenkins

USER jenkins